config/routes.rb
Rails.application.routes.draw do
  get 'timelines/index'

  devise_for :users, controllers: { sessions: "users/sessions", confirmations: "users/confirmations", passwords: "users/passwords", registrations: "users/registrations", unlocks: "users/unlocks" } do
  end
  root :to => 'statics#home'
  resources :status

  resources :timelines do
    collection do
      post :create_status
      post :create_comment
      post :toggle_likes
    end
  end
end

app/views/layouts/_navbar.html.slim
nav.top-bar.navbar data-topbar="" role="navigation"
  ul.title-area
    li.name
      h1
        a href="/"  Lintang Arief
    /! Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    li.toggle-topbar.menu-icon
      a href="#" 
        span Menu
  section.top-bar-section
    /! Right Nav Section
    ul.right
      - if current_user.nil?
        li.active
          = link_to "Sign up", new_user_registration_path()
        li.active
          = link_to "Log in", new_user_session_path()
      -else
        li.active
          = link_to "TIMELINE", timelines_index_path()
      li.has-dropdown
        a href="#"  Help
        ul.dropdown
          - if current_user.nil?
            li
              = link_to "Forgot Password", edit_user_password_path(), method: :DELETE
          - else
            li
              = link_to('Logout', destroy_user_session_path, :method => :delete) 
          li.active
            a href="#"  About
    /! Left Nav Section

app/views/layouts/application.html.slim
doctype html
== "<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->"
== "<!--[if lt IE 7 ]> <html class=\"ie6\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 7 ]>    <html class=\"ie7\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 8 ]>    <html class=\"ie8\" lang=\"en\"> <![endif]-->"
== "<!--[if IE 9 ]>    <html class=\"ie9\" lang=\"en\"> <![endif]-->"
== "<!--[if (gt IE 9)|!(IE)]><!--> <html lang=\"en\"> <!--<![endif]-->"

head
  meta charset="utf-8"

  / Uncomment to make IE8 render like IE7
  / meta http-equiv="X-UA-Compatible" content="IE=7"

  / Set the viewport width to device width for mobile
  meta name="viewport" content="width=device-width, initial-scale=1.0"

  / title= content_for?(:title) ? yield(:title) : "Untitled"

  = stylesheet_link_tag "application"
  = javascript_include_tag "vendor/modernizr"

  = csrf_meta_tag

body
  = render "layouts/navbar"
  == yield

  = javascript_include_tag "application"